version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
  php:
    build:
      context: .
      dockerfile: docker/PHP.Dockerfile
    volumes:
      - ./:/app
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'etoa-web'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'etoa-web'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysqldata: {}
