on:
  push:
    branches:
      - production
env:
  PHP_VERSION: '8.0'
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    - name: Setup PHP
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist  --optimize-autoloader --no-dev
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        exclude: .git*
          - .git*/**
          - node_modules/**
          - node_modules/**/*
          - _db
          - _db/**
          - archiv
          - archiv/**
          - downloads
          - downloads/**
          - forum
          - forum/**
          - testforum
          - testforum/**
          - zeitung
          - zeitung/**
          - .ftpquota
