name: Deploy to Production

on:
  push:
    branches:
      - production

env:
  PHP_VERSION: "8.1"
  NODE_VERSION: "16.x"

jobs:
  check-secret:
    name: Check repository secrets
    runs-on: ubuntu-latest
    outputs:
      ftp-data: ${{ steps.ftp-data.outputs.defined }}
    steps:
      - id: ftp-data
        if: "${{ env.FTP_SERVER != '' && env.FTP_USERNAME != '' && env.FTP_PASSWORD != ''}}"
        run: echo "::set-output name=defined::true"
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [check-secret]
    if: (github.repository == 'etoa/etoa-web' && needs.check-secret.outputs.ftp-data == 'true')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Install PHP dependencies via Composer
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist  --optimize-autoloader --no-dev
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install packages via NPM
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Add clear cache trigger
        run: touch storage/clear_cache.trigger
      - name: Log git info
        shell: bash
        run: |
          echo "Commit: $(git rev-parse --short HEAD)" >> gitinfo
          echo "Branch: ${GITHUB_REF#refs/heads/}" >> gitinfo
          echo "Build date: $(date)" >> gitinfo
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/docker/**
            public/archiv/**
            public/pub/**
            .ftpquota
            .editorconfig
            .php-cs*
            docker*
            phpstan*
            *.md
            package*.json
            composer.*
            webpack.*
            resources/**
